### ISSUE TITLE
myflightradar24 data import issues

### ISSUE THREAD

**Issue by mooaw** [tsfu/airlog#6]
I noticed two issues while importing my flight data.

1. Aircraft type Boeing 777-200ER (B77E) could not be recognized.
2. The last five rows of data/flights were missing. I didn't find any similarities between the missing rows.

**Comment by tsfu** [comment]
TODO:
1. 777-200ER currently shares code B772/772 in IATA/ICAO system, will use B77E/77E for it if there is no conflict. You can see that in /data/aircrafts.json and edit the file if you want.
2. It might be an unknown airline/aircraft error that stopped the import. Will look into this issue later.

**Comment by tsfu** [comment]
Fixed in commits on Oct 28:

1. Added "B77E/77E" for 777-200ER only, and keeping "B772/772" for both models,
2. Completed airline "KN/CUA" and airport "NAY",
3. Added date format and IATA code check for FR24 .csv import, will skip trip(s) with invalid IATA.
