### ISSUE TITLE
Visualize the number of flights and airport visits

### ISSUE THREAD

**Issue by mooaw** [tsfu/airlog#7]
In the Globe view, can you add features that indicate the number of flights and airport visits?

For example, the number of flights between two airports can be visualized by different colors (similar to the realization of myflightradar24) or line weights. The number of airport visits can be shown by the symbol size.

**Comment by tsfu** [comment]
TODO:

Set frequency tiers in routes and airports data in stats.js, then draw differently in Cesium API calls.

**Comment by tsfu** [comment]
Added this feature in commit 2da3529 of v1.2.0 WIP. 

Also addressed the issue where Cesium draws multiple layers (identical without adding frequency tier) on a multi-visited route/city.
